from Module import *

rus=[]
eng=[]
rus=loe_fail("rus.txt")
eng=loe_fail("eng.txt")
win=Tk()
win.title('Словарь')
win.geometry('600x500')
tab_control=ttk.Notebook(win)
tab1=Frame(tab_control)
tab2=Frame(tab_control)
tab3=Frame(tab_control)
tab_control.add(tab1,text="Перевод")#, command=lambda: [loe_fail("rus.txt"), loe_fail("eng.txt")])
tab_control.add(tab2,text="Добавление слов")
tab_control.add(tab3,text="Исправление ошибок")
#первая вкладка
title=Label(tab1,text="Англо-русский и русско-английский словарь",height=3)
entlbl=Label(tab1,text="Введите слово:",height=3)
sonavar=StringVar()
ent=Entry(tab1,textvariable=sonavar,width=40)
btn=Button(tab1,text="Перевести",height=3,command=lambda: [tolkimine(sonavar,rus,eng,anslbl), ent.delete(0,END)])
btn2=Button(tab1,text="Перевести и озвучить",height=3,command=lambda: [audio(sonavar,rus,eng,anslbl), ent.delete(0,END)])
anslbl=Label(tab1, text="Перевод слова появится здесь", height=3)
#pack 1 вкладки
title.pack()
entlbl.pack()
ent.pack()
btn.pack()
btn2.pack()
anslbl.pack()
#вторая вкладка
title2=Label(tab2, text="Добавить слово в словарь")
ruswlbl=Label(tab2, text="Слово на русском языке")
rusword=StringVar()
rusentry=Entry(tab2,textvariable=rusword,width=40)
engwlbl=Label(tab2, text="Слово на английском языке")
engword=StringVar()
engentry=Entry(tab2,textvariable=engword,width=40)
btnw=Button(tab2,text="Добавить в словарь",height=3,command=lambda: [kirjuta_rus("rus.txt",rusword,anslblwrus,rus), rusentry.delete(0,END), kirjuta_eng("eng.txt",engword,anslblweng,eng), engentry.delete(0,END)])
anslblwrus=Label(tab2, text="", height=3)
anslblweng=Label(tab2, text="", height=3)
#pack 2 вкладки
title2.pack()
ruswlbl.pack()
rusentry.pack()
engwlbl.pack()
engentry.pack()
btnw.pack()
anslblwrus.pack()
anslblweng.pack()
#третья вкладка
title3=Label(tab3, text="Исправление ошибок")
para1=Label(tab3, text="Неправильная пара слов", height=3)
rvlbl=Label(tab3,text="Слово на русском:")
rvvar=StringVar()
rvent=Entry(tab3,textvariable=rvvar,width=40)
evlbl=Label(tab3,text="Слово на английском:")
evvar=StringVar()
event=Entry(tab3,textvariable=evvar,width=40)
para2=Label(tab3, text="Правильная пара слов",height=3)
rolbl=Label(tab3,text="Слово на русском:")
rovar=StringVar()
roent=Entry(tab3,textvariable=rovar,width=40)
eolbl=Label(tab3,text="Слово на английском:")
eovar=StringVar()
eoent=Entry(tab3,textvariable=eovar,width=40)
btn3=Button(tab3,text="Исправить",height=3,command=lambda: [paranda("rus.txt",rus,rvvar,rovar,"eng.txt",eng,evvar,eovar,anslbl3), rvent.delete(0,END), roent.delete(0,END), event.delete(0,END), eoent.delete(0,END)])
anslbl3=Label(tab3, text="", height=3)
#pack 3 вкладки
title3.pack()
para1.pack()
rvlbl.pack()
rvent.pack()
evlbl.pack()
event.pack()
para2.pack()
rolbl.pack()
roent.pack()
eolbl.pack()
eoent.pack()
btn3.pack()
anslbl3.pack()
#конец окна
tab_control.pack(expand=1,fill="both")
win.mainloop()
        

